#!/usr/bin/env python3

from os import execlp, environ
from pathlib import Path
oxygen_home = environ.get('OXYGEN_HOME')
assert oxygen_home is not None, '$OXYGEN_HOME not set'

dita_ot_home = Path(oxygen_home) / 'frameworks' / 'dita' / 'DITA-OT'
assert dita_ot_home.is_dir(), f'{dita_ot_home} is not a directory'
dita_ot_bin = (dita_ot_home / 'bin' / 'dita').as_posix()

dtabf_dir = (Path(__file__) / '..' / '..').resolve()
doc_dir = dtabf_dir / 'documentation'

execlp(
    dita_ot_bin, dita_ot_bin,
    '-i',  (doc_dir / 'dtabf.ditamap').as_posix(),
    '-o',  (dtabf_dir / 'htdocs').as_posix(),
    '-f', 'webhelp-responsive',
    '--args.css', 'skin.css',
    '--args.csspath', 'style/',
    '--args.cssroot', (doc_dir / 'style').as_posix(),
    '--args.copycss', 'yes',
    '--default.language', 'de-de',
    '--force-unique', 'true',
    '--webhelp.custom.resources', (doc_dir / 'resources').as_posix(),
    '--webhelp.favicon', (doc_dir / 'img' / 'dtabf.ico').as_posix(),
    '--webhelp.fragment.footer', (doc_dir / 'style' / 'snippet_footer.html').as_posix(),
    '--webhelp.fragment.welcome', 'DTA-Basisformat',
    '--webhelp.logo.image', (doc_dir / 'img' / 'dtabf_logo.svg').as_posix()
)
